#!/bin/bash

#sets the username of the system, supervisord does not have a login
#so we need to use the who command. 
HOMENAME=`who | head -n1 | cut -d " " -f1`

export HOME="/home/$HOMENAME/JoustMania"

exec $HOME/venv/bin/python3.6 -m unittest discover -s . -p '*_test.py'
