# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import controller_manager_mock_pb2 as controller__manager__mock__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in controller_manager_mock_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MockControllerServiceStub(object):
    """Additional RPCs for mock controller control
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SimulateMovement = channel.unary_unary(
                '/controller_manager_mock.MockControllerService/SimulateMovement',
                request_serializer=controller__manager__mock__pb2.MovementRequest.SerializeToString,
                response_deserializer=controller__manager__mock__pb2.MovementResponse.FromString,
                _registered_method=True)
        self.SimulateDeath = channel.unary_unary(
                '/controller_manager_mock.MockControllerService/SimulateDeath',
                request_serializer=controller__manager__mock__pb2.DeathRequest.SerializeToString,
                response_deserializer=controller__manager__mock__pb2.DeathResponse.FromString,
                _registered_method=True)
        self.SimulateButton = channel.unary_unary(
                '/controller_manager_mock.MockControllerService/SimulateButton',
                request_serializer=controller__manager__mock__pb2.ButtonRequest.SerializeToString,
                response_deserializer=controller__manager__mock__pb2.ButtonResponse.FromString,
                _registered_method=True)
        self.SetColor = channel.unary_unary(
                '/controller_manager_mock.MockControllerService/SetColor',
                request_serializer=controller__manager__mock__pb2.ColorRequest.SerializeToString,
                response_deserializer=controller__manager__mock__pb2.ColorResponse.FromString,
                _registered_method=True)
        self.ResetController = channel.unary_unary(
                '/controller_manager_mock.MockControllerService/ResetController',
                request_serializer=controller__manager__mock__pb2.ResetRequest.SerializeToString,
                response_deserializer=controller__manager__mock__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.ListMockControllers = channel.unary_unary(
                '/controller_manager_mock.MockControllerService/ListMockControllers',
                request_serializer=controller__manager__mock__pb2.ListRequest.SerializeToString,
                response_deserializer=controller__manager__mock__pb2.ListResponse.FromString,
                _registered_method=True)


class MockControllerServiceServicer(object):
    """Additional RPCs for mock controller control
    """

    def SimulateMovement(self, request, context):
        """Simulate controller movement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimulateDeath(self, request, context):
        """Simulate death (high acceleration)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimulateButton(self, request, context):
        """Simulate button press
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetColor(self, request, context):
        """Set LED color
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetController(self, request, context):
        """Reset controller to idle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMockControllers(self, request, context):
        """Get list of mock controllers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MockControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SimulateMovement': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateMovement,
                    request_deserializer=controller__manager__mock__pb2.MovementRequest.FromString,
                    response_serializer=controller__manager__mock__pb2.MovementResponse.SerializeToString,
            ),
            'SimulateDeath': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateDeath,
                    request_deserializer=controller__manager__mock__pb2.DeathRequest.FromString,
                    response_serializer=controller__manager__mock__pb2.DeathResponse.SerializeToString,
            ),
            'SimulateButton': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateButton,
                    request_deserializer=controller__manager__mock__pb2.ButtonRequest.FromString,
                    response_serializer=controller__manager__mock__pb2.ButtonResponse.SerializeToString,
            ),
            'SetColor': grpc.unary_unary_rpc_method_handler(
                    servicer.SetColor,
                    request_deserializer=controller__manager__mock__pb2.ColorRequest.FromString,
                    response_serializer=controller__manager__mock__pb2.ColorResponse.SerializeToString,
            ),
            'ResetController': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetController,
                    request_deserializer=controller__manager__mock__pb2.ResetRequest.FromString,
                    response_serializer=controller__manager__mock__pb2.ResetResponse.SerializeToString,
            ),
            'ListMockControllers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMockControllers,
                    request_deserializer=controller__manager__mock__pb2.ListRequest.FromString,
                    response_serializer=controller__manager__mock__pb2.ListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'controller_manager_mock.MockControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('controller_manager_mock.MockControllerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MockControllerService(object):
    """Additional RPCs for mock controller control
    """

    @staticmethod
    def SimulateMovement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller_manager_mock.MockControllerService/SimulateMovement',
            controller__manager__mock__pb2.MovementRequest.SerializeToString,
            controller__manager__mock__pb2.MovementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimulateDeath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller_manager_mock.MockControllerService/SimulateDeath',
            controller__manager__mock__pb2.DeathRequest.SerializeToString,
            controller__manager__mock__pb2.DeathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimulateButton(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller_manager_mock.MockControllerService/SimulateButton',
            controller__manager__mock__pb2.ButtonRequest.SerializeToString,
            controller__manager__mock__pb2.ButtonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetColor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller_manager_mock.MockControllerService/SetColor',
            controller__manager__mock__pb2.ColorRequest.SerializeToString,
            controller__manager__mock__pb2.ColorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetController(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller_manager_mock.MockControllerService/ResetController',
            controller__manager__mock__pb2.ResetRequest.SerializeToString,
            controller__manager__mock__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMockControllers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller_manager_mock.MockControllerService/ListMockControllers',
            controller__manager__mock__pb2.ListRequest.SerializeToString,
            controller__manager__mock__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
