# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import settings_pb2 as settings__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in settings_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SettingsServiceStub(object):
    """Settings Service - Manages game configuration and settings
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSettings = channel.unary_unary(
                '/joustmania.settings.SettingsService/GetSettings',
                request_serializer=settings__pb2.GetSettingsRequest.SerializeToString,
                response_deserializer=settings__pb2.GetSettingsResponse.FromString,
                _registered_method=True)
        self.GetSetting = channel.unary_unary(
                '/joustmania.settings.SettingsService/GetSetting',
                request_serializer=settings__pb2.GetSettingRequest.SerializeToString,
                response_deserializer=settings__pb2.GetSettingResponse.FromString,
                _registered_method=True)
        self.UpdateSetting = channel.unary_unary(
                '/joustmania.settings.SettingsService/UpdateSetting',
                request_serializer=settings__pb2.UpdateSettingRequest.SerializeToString,
                response_deserializer=settings__pb2.UpdateSettingResponse.FromString,
                _registered_method=True)
        self.SubscribeToChanges = channel.unary_stream(
                '/joustmania.settings.SettingsService/SubscribeToChanges',
                request_serializer=settings__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=settings__pb2.SettingChangeEvent.FromString,
                _registered_method=True)


class SettingsServiceServicer(object):
    """Settings Service - Manages game configuration and settings
    """

    def GetSettings(self, request, context):
        """Get all settings as a map
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSetting(self, request, context):
        """Get a specific setting by key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSetting(self, request, context):
        """Update a specific setting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToChanges(self, request, context):
        """Subscribe to setting change events (server-side streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SettingsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSettings,
                    request_deserializer=settings__pb2.GetSettingsRequest.FromString,
                    response_serializer=settings__pb2.GetSettingsResponse.SerializeToString,
            ),
            'GetSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSetting,
                    request_deserializer=settings__pb2.GetSettingRequest.FromString,
                    response_serializer=settings__pb2.GetSettingResponse.SerializeToString,
            ),
            'UpdateSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSetting,
                    request_deserializer=settings__pb2.UpdateSettingRequest.FromString,
                    response_serializer=settings__pb2.UpdateSettingResponse.SerializeToString,
            ),
            'SubscribeToChanges': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToChanges,
                    request_deserializer=settings__pb2.SubscribeRequest.FromString,
                    response_serializer=settings__pb2.SettingChangeEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'joustmania.settings.SettingsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('joustmania.settings.SettingsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SettingsService(object):
    """Settings Service - Manages game configuration and settings
    """

    @staticmethod
    def GetSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.settings.SettingsService/GetSettings',
            settings__pb2.GetSettingsRequest.SerializeToString,
            settings__pb2.GetSettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.settings.SettingsService/GetSetting',
            settings__pb2.GetSettingRequest.SerializeToString,
            settings__pb2.GetSettingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.settings.SettingsService/UpdateSetting',
            settings__pb2.UpdateSettingRequest.SerializeToString,
            settings__pb2.UpdateSettingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/joustmania.settings.SettingsService/SubscribeToChanges',
            settings__pb2.SubscribeRequest.SerializeToString,
            settings__pb2.SettingChangeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
