# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: settings.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'settings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esettings.proto\x12\x13joustmania.settings\"\x14\n\x12GetSettingsRequest\"\xb0\x01\n\x13GetSettingsResponse\x12H\n\x08settings\x18\x01 \x03(\x0b\x32\x36.joustmania.settings.GetSettingsResponse.SettingsEntry\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x1a/\n\rSettingsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\" \n\x11GetSettingRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"P\n\x12GetSettingResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"B\n\x14UpdateSettingRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\"]\n\x15UpdateSettingResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x11\n\told_value\x18\x03 \x01(\t\x12\x11\n\tnew_value\x18\x04 \x01(\t\" \n\x10SubscribeRequest\x12\x0c\n\x04keys\x18\x01 \x03(\t\"j\n\x12SettingChangeEvent\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x11\n\told_value\x18\x02 \x01(\t\x12\x11\n\tnew_value\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x32\xa2\x03\n\x0fSettingsService\x12`\n\x0bGetSettings\x12\'.joustmania.settings.GetSettingsRequest\x1a(.joustmania.settings.GetSettingsResponse\x12]\n\nGetSetting\x12&.joustmania.settings.GetSettingRequest\x1a\'.joustmania.settings.GetSettingResponse\x12\x66\n\rUpdateSetting\x12).joustmania.settings.UpdateSettingRequest\x1a*.joustmania.settings.UpdateSettingResponse\x12\x66\n\x12SubscribeToChanges\x12%.joustmania.settings.SubscribeRequest\x1a\'.joustmania.settings.SettingChangeEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'settings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSETTINGSRESPONSE_SETTINGSENTRY']._loaded_options = None
  _globals['_GETSETTINGSRESPONSE_SETTINGSENTRY']._serialized_options = b'8\001'
  _globals['_GETSETTINGSREQUEST']._serialized_start=39
  _globals['_GETSETTINGSREQUEST']._serialized_end=59
  _globals['_GETSETTINGSRESPONSE']._serialized_start=62
  _globals['_GETSETTINGSRESPONSE']._serialized_end=238
  _globals['_GETSETTINGSRESPONSE_SETTINGSENTRY']._serialized_start=191
  _globals['_GETSETTINGSRESPONSE_SETTINGSENTRY']._serialized_end=238
  _globals['_GETSETTINGREQUEST']._serialized_start=240
  _globals['_GETSETTINGREQUEST']._serialized_end=272
  _globals['_GETSETTINGRESPONSE']._serialized_start=274
  _globals['_GETSETTINGRESPONSE']._serialized_end=354
  _globals['_UPDATESETTINGREQUEST']._serialized_start=356
  _globals['_UPDATESETTINGREQUEST']._serialized_end=422
  _globals['_UPDATESETTINGRESPONSE']._serialized_start=424
  _globals['_UPDATESETTINGRESPONSE']._serialized_end=517
  _globals['_SUBSCRIBEREQUEST']._serialized_start=519
  _globals['_SUBSCRIBEREQUEST']._serialized_end=551
  _globals['_SETTINGCHANGEEVENT']._serialized_start=553
  _globals['_SETTINGCHANGEEVENT']._serialized_end=659
  _globals['_SETTINGSSERVICE']._serialized_start=662
  _globals['_SETTINGSSERVICE']._serialized_end=1080
# @@protoc_insertion_point(module_scope)
