# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from services.game_coordinator import game_coordinator_pb2 as game__coordinator__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in game_coordinator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameCoordinatorServiceStub(object):
    """GameCoordinator Service - Manages game lifecycle and coordination
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartGame = channel.unary_unary(
                '/joustmania.game_coordinator.GameCoordinatorService/StartGame',
                request_serializer=game__coordinator__pb2.StartGameRequest.SerializeToString,
                response_deserializer=game__coordinator__pb2.StartGameResponse.FromString,
                _registered_method=True)
        self.GetGameStatus = channel.unary_unary(
                '/joustmania.game_coordinator.GameCoordinatorService/GetGameStatus',
                request_serializer=game__coordinator__pb2.GetGameStatusRequest.SerializeToString,
                response_deserializer=game__coordinator__pb2.GetGameStatusResponse.FromString,
                _registered_method=True)
        self.ForceEndGame = channel.unary_unary(
                '/joustmania.game_coordinator.GameCoordinatorService/ForceEndGame',
                request_serializer=game__coordinator__pb2.ForceEndGameRequest.SerializeToString,
                response_deserializer=game__coordinator__pb2.ForceEndGameResponse.FromString,
                _registered_method=True)
        self.StreamGameEvents = channel.unary_stream(
                '/joustmania.game_coordinator.GameCoordinatorService/StreamGameEvents',
                request_serializer=game__coordinator__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=game__coordinator__pb2.GameEvent.FromString,
                _registered_method=True)


class GameCoordinatorServiceServicer(object):
    """GameCoordinator Service - Manages game lifecycle and coordination
    """

    def StartGame(self, request, context):
        """Start a game
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGameStatus(self, request, context):
        """Get current game status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForceEndGame(self, request, context):
        """Force end current game
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGameEvents(self, request, context):
        """Stream game events (deaths, scoring, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameCoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartGame': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGame,
                    request_deserializer=game__coordinator__pb2.StartGameRequest.FromString,
                    response_serializer=game__coordinator__pb2.StartGameResponse.SerializeToString,
            ),
            'GetGameStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameStatus,
                    request_deserializer=game__coordinator__pb2.GetGameStatusRequest.FromString,
                    response_serializer=game__coordinator__pb2.GetGameStatusResponse.SerializeToString,
            ),
            'ForceEndGame': grpc.unary_unary_rpc_method_handler(
                    servicer.ForceEndGame,
                    request_deserializer=game__coordinator__pb2.ForceEndGameRequest.FromString,
                    response_serializer=game__coordinator__pb2.ForceEndGameResponse.SerializeToString,
            ),
            'StreamGameEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGameEvents,
                    request_deserializer=game__coordinator__pb2.StreamEventsRequest.FromString,
                    response_serializer=game__coordinator__pb2.GameEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'joustmania.game_coordinator.GameCoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('joustmania.game_coordinator.GameCoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameCoordinatorService(object):
    """GameCoordinator Service - Manages game lifecycle and coordination
    """

    @staticmethod
    def StartGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.game_coordinator.GameCoordinatorService/StartGame',
            game__coordinator__pb2.StartGameRequest.SerializeToString,
            game__coordinator__pb2.StartGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGameStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.game_coordinator.GameCoordinatorService/GetGameStatus',
            game__coordinator__pb2.GetGameStatusRequest.SerializeToString,
            game__coordinator__pb2.GetGameStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForceEndGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.game_coordinator.GameCoordinatorService/ForceEndGame',
            game__coordinator__pb2.ForceEndGameRequest.SerializeToString,
            game__coordinator__pb2.ForceEndGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGameEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/joustmania.game_coordinator.GameCoordinatorService/StreamGameEvents',
            game__coordinator__pb2.StreamEventsRequest.SerializeToString,
            game__coordinator__pb2.GameEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
