# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import audio_pb2 as audio__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in audio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioServiceStub(object):
    """Audio Service - Manages audio playback and mixing
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlaySound = channel.unary_unary(
                '/joustmania.audio.AudioService/PlaySound',
                request_serializer=audio__pb2.PlaySoundRequest.SerializeToString,
                response_deserializer=audio__pb2.PlaySoundResponse.FromString,
                _registered_method=True)
        self.PlayMusic = channel.unary_unary(
                '/joustmania.audio.AudioService/PlayMusic',
                request_serializer=audio__pb2.PlayMusicRequest.SerializeToString,
                response_deserializer=audio__pb2.PlayMusicResponse.FromString,
                _registered_method=True)
        self.StopMusic = channel.unary_unary(
                '/joustmania.audio.AudioService/StopMusic',
                request_serializer=audio__pb2.StopMusicRequest.SerializeToString,
                response_deserializer=audio__pb2.StopMusicResponse.FromString,
                _registered_method=True)
        self.ChangeTempo = channel.unary_unary(
                '/joustmania.audio.AudioService/ChangeTempo',
                request_serializer=audio__pb2.ChangeTempoRequest.SerializeToString,
                response_deserializer=audio__pb2.ChangeTempoResponse.FromString,
                _registered_method=True)
        self.SetVolume = channel.unary_unary(
                '/joustmania.audio.AudioService/SetVolume',
                request_serializer=audio__pb2.SetVolumeRequest.SerializeToString,
                response_deserializer=audio__pb2.SetVolumeResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/joustmania.audio.AudioService/GetStatus',
                request_serializer=audio__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=audio__pb2.GetStatusResponse.FromString,
                _registered_method=True)


class AudioServiceServicer(object):
    """Audio Service - Manages audio playback and mixing
    """

    def PlaySound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayMusic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopMusic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeTempo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlaySound': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaySound,
                    request_deserializer=audio__pb2.PlaySoundRequest.FromString,
                    response_serializer=audio__pb2.PlaySoundResponse.SerializeToString,
            ),
            'PlayMusic': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayMusic,
                    request_deserializer=audio__pb2.PlayMusicRequest.FromString,
                    response_serializer=audio__pb2.PlayMusicResponse.SerializeToString,
            ),
            'StopMusic': grpc.unary_unary_rpc_method_handler(
                    servicer.StopMusic,
                    request_deserializer=audio__pb2.StopMusicRequest.FromString,
                    response_serializer=audio__pb2.StopMusicResponse.SerializeToString,
            ),
            'ChangeTempo': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeTempo,
                    request_deserializer=audio__pb2.ChangeTempoRequest.FromString,
                    response_serializer=audio__pb2.ChangeTempoResponse.SerializeToString,
            ),
            'SetVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVolume,
                    request_deserializer=audio__pb2.SetVolumeRequest.FromString,
                    response_serializer=audio__pb2.SetVolumeResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=audio__pb2.GetStatusRequest.FromString,
                    response_serializer=audio__pb2.GetStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'joustmania.audio.AudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('joustmania.audio.AudioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioService(object):
    """Audio Service - Manages audio playback and mixing
    """

    @staticmethod
    def PlaySound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.audio.AudioService/PlaySound',
            audio__pb2.PlaySoundRequest.SerializeToString,
            audio__pb2.PlaySoundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayMusic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.audio.AudioService/PlayMusic',
            audio__pb2.PlayMusicRequest.SerializeToString,
            audio__pb2.PlayMusicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopMusic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.audio.AudioService/StopMusic',
            audio__pb2.StopMusicRequest.SerializeToString,
            audio__pb2.StopMusicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeTempo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.audio.AudioService/ChangeTempo',
            audio__pb2.ChangeTempoRequest.SerializeToString,
            audio__pb2.ChangeTempoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.audio.AudioService/SetVolume',
            audio__pb2.SetVolumeRequest.SerializeToString,
            audio__pb2.SetVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.audio.AudioService/GetStatus',
            audio__pb2.GetStatusRequest.SerializeToString,
            audio__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
