# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import controller_manager_pb2 as controller__manager__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in controller_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControllerManagerServiceStub(object):
    """ControllerManager Service - Manages PS Move controllers
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetControllerCount = channel.unary_unary(
                '/joustmania.controller_manager.ControllerManagerService/GetControllerCount',
                request_serializer=controller__manager__pb2.GetControllerCountRequest.SerializeToString,
                response_deserializer=controller__manager__pb2.GetControllerCountResponse.FromString,
                _registered_method=True)
        self.GetControllers = channel.unary_unary(
                '/joustmania.controller_manager.ControllerManagerService/GetControllers',
                request_serializer=controller__manager__pb2.GetControllersRequest.SerializeToString,
                response_deserializer=controller__manager__pb2.GetControllersResponse.FromString,
                _registered_method=True)
        self.StreamControllerStates = channel.unary_stream(
                '/joustmania.controller_manager.ControllerManagerService/StreamControllerStates',
                request_serializer=controller__manager__pb2.StreamRequest.SerializeToString,
                response_deserializer=controller__manager__pb2.ControllerStateUpdate.FromString,
                _registered_method=True)
        self.StreamButtonEvents = channel.stream_stream(
                '/joustmania.controller_manager.ControllerManagerService/StreamButtonEvents',
                request_serializer=controller__manager__pb2.ButtonEventStreamControl.SerializeToString,
                response_deserializer=controller__manager__pb2.ButtonEvent.FromString,
                _registered_method=True)
        self.StreamGameplayData = channel.unary_stream(
                '/joustmania.controller_manager.ControllerManagerService/StreamGameplayData',
                request_serializer=controller__manager__pb2.GameplayStreamRequest.SerializeToString,
                response_deserializer=controller__manager__pb2.GameplayDataUpdate.FromString,
                _registered_method=True)
        self.StreamGameplayDataDynamic = channel.stream_stream(
                '/joustmania.controller_manager.ControllerManagerService/StreamGameplayDataDynamic',
                request_serializer=controller__manager__pb2.GameplayStreamControl.SerializeToString,
                response_deserializer=controller__manager__pb2.GameplayDataUpdate.FromString,
                _registered_method=True)
        self.PairController = channel.unary_unary(
                '/joustmania.controller_manager.ControllerManagerService/PairController',
                request_serializer=controller__manager__pb2.PairControllerRequest.SerializeToString,
                response_deserializer=controller__manager__pb2.PairControllerResponse.FromString,
                _registered_method=True)
        self.RemoveController = channel.unary_unary(
                '/joustmania.controller_manager.ControllerManagerService/RemoveController',
                request_serializer=controller__manager__pb2.RemoveControllerRequest.SerializeToString,
                response_deserializer=controller__manager__pb2.RemoveControllerResponse.FromString,
                _registered_method=True)
        self.SetControllerColor = channel.unary_unary(
                '/joustmania.controller_manager.ControllerManagerService/SetControllerColor',
                request_serializer=controller__manager__pb2.SetControllerColorRequest.SerializeToString,
                response_deserializer=controller__manager__pb2.SetControllerColorResponse.FromString,
                _registered_method=True)
        self.SetControllerVibration = channel.unary_unary(
                '/joustmania.controller_manager.ControllerManagerService/SetControllerVibration',
                request_serializer=controller__manager__pb2.SetControllerVibrationRequest.SerializeToString,
                response_deserializer=controller__manager__pb2.SetControllerVibrationResponse.FromString,
                _registered_method=True)
        self.PlayControllerEffect = channel.unary_unary(
                '/joustmania.controller_manager.ControllerManagerService/PlayControllerEffect',
                request_serializer=controller__manager__pb2.PlayControllerEffectRequest.SerializeToString,
                response_deserializer=controller__manager__pb2.PlayControllerEffectResponse.FromString,
                _registered_method=True)


class ControllerManagerServiceServicer(object):
    """ControllerManager Service - Manages PS Move controllers
    """

    def GetControllerCount(self, request, context):
        """Get controller count
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetControllers(self, request, context):
        """Get all controller states
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamControllerStates(self, request, context):
        """Stream controller states (real-time updates)
        DEPRECATED: Use StreamButtonEvents for menu/UI and StreamGameplayData for games
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamButtonEvents(self, request_iterator, context):
        """Stream button press/release events (Phase 41 - event-driven for menu/UI)
        Phase XX: Made bidirectional for LED state ownership - menu can send base colors and effects
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGameplayData(self, request, context):
        """Stream gameplay data (acceleration/gyro only, Phase 41 - for game modes)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGameplayDataDynamic(self, request_iterator, context):
        """Stream gameplay data with dynamic filtering (Phase 45 - bidirectional streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PairController(self, request, context):
        """Pair a new controller
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveController(self, request, context):
        """Remove a controller
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetControllerColor(self, request, context):
        """Controller feedback RPCs (Phase 19)
        Set LED color
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetControllerVibration(self, request, context):
        """Set vibration intensity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayControllerEffect(self, request, context):
        """Play predefined effect (flash, pulse, rainbow, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetControllerCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetControllerCount,
                    request_deserializer=controller__manager__pb2.GetControllerCountRequest.FromString,
                    response_serializer=controller__manager__pb2.GetControllerCountResponse.SerializeToString,
            ),
            'GetControllers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetControllers,
                    request_deserializer=controller__manager__pb2.GetControllersRequest.FromString,
                    response_serializer=controller__manager__pb2.GetControllersResponse.SerializeToString,
            ),
            'StreamControllerStates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamControllerStates,
                    request_deserializer=controller__manager__pb2.StreamRequest.FromString,
                    response_serializer=controller__manager__pb2.ControllerStateUpdate.SerializeToString,
            ),
            'StreamButtonEvents': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamButtonEvents,
                    request_deserializer=controller__manager__pb2.ButtonEventStreamControl.FromString,
                    response_serializer=controller__manager__pb2.ButtonEvent.SerializeToString,
            ),
            'StreamGameplayData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGameplayData,
                    request_deserializer=controller__manager__pb2.GameplayStreamRequest.FromString,
                    response_serializer=controller__manager__pb2.GameplayDataUpdate.SerializeToString,
            ),
            'StreamGameplayDataDynamic': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamGameplayDataDynamic,
                    request_deserializer=controller__manager__pb2.GameplayStreamControl.FromString,
                    response_serializer=controller__manager__pb2.GameplayDataUpdate.SerializeToString,
            ),
            'PairController': grpc.unary_unary_rpc_method_handler(
                    servicer.PairController,
                    request_deserializer=controller__manager__pb2.PairControllerRequest.FromString,
                    response_serializer=controller__manager__pb2.PairControllerResponse.SerializeToString,
            ),
            'RemoveController': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveController,
                    request_deserializer=controller__manager__pb2.RemoveControllerRequest.FromString,
                    response_serializer=controller__manager__pb2.RemoveControllerResponse.SerializeToString,
            ),
            'SetControllerColor': grpc.unary_unary_rpc_method_handler(
                    servicer.SetControllerColor,
                    request_deserializer=controller__manager__pb2.SetControllerColorRequest.FromString,
                    response_serializer=controller__manager__pb2.SetControllerColorResponse.SerializeToString,
            ),
            'SetControllerVibration': grpc.unary_unary_rpc_method_handler(
                    servicer.SetControllerVibration,
                    request_deserializer=controller__manager__pb2.SetControllerVibrationRequest.FromString,
                    response_serializer=controller__manager__pb2.SetControllerVibrationResponse.SerializeToString,
            ),
            'PlayControllerEffect': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayControllerEffect,
                    request_deserializer=controller__manager__pb2.PlayControllerEffectRequest.FromString,
                    response_serializer=controller__manager__pb2.PlayControllerEffectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'joustmania.controller_manager.ControllerManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('joustmania.controller_manager.ControllerManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControllerManagerService(object):
    """ControllerManager Service - Manages PS Move controllers
    """

    @staticmethod
    def GetControllerCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.controller_manager.ControllerManagerService/GetControllerCount',
            controller__manager__pb2.GetControllerCountRequest.SerializeToString,
            controller__manager__pb2.GetControllerCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetControllers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.controller_manager.ControllerManagerService/GetControllers',
            controller__manager__pb2.GetControllersRequest.SerializeToString,
            controller__manager__pb2.GetControllersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamControllerStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/joustmania.controller_manager.ControllerManagerService/StreamControllerStates',
            controller__manager__pb2.StreamRequest.SerializeToString,
            controller__manager__pb2.ControllerStateUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamButtonEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/joustmania.controller_manager.ControllerManagerService/StreamButtonEvents',
            controller__manager__pb2.ButtonEventStreamControl.SerializeToString,
            controller__manager__pb2.ButtonEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGameplayData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/joustmania.controller_manager.ControllerManagerService/StreamGameplayData',
            controller__manager__pb2.GameplayStreamRequest.SerializeToString,
            controller__manager__pb2.GameplayDataUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGameplayDataDynamic(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/joustmania.controller_manager.ControllerManagerService/StreamGameplayDataDynamic',
            controller__manager__pb2.GameplayStreamControl.SerializeToString,
            controller__manager__pb2.GameplayDataUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PairController(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.controller_manager.ControllerManagerService/PairController',
            controller__manager__pb2.PairControllerRequest.SerializeToString,
            controller__manager__pb2.PairControllerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveController(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.controller_manager.ControllerManagerService/RemoveController',
            controller__manager__pb2.RemoveControllerRequest.SerializeToString,
            controller__manager__pb2.RemoveControllerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetControllerColor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.controller_manager.ControllerManagerService/SetControllerColor',
            controller__manager__pb2.SetControllerColorRequest.SerializeToString,
            controller__manager__pb2.SetControllerColorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetControllerVibration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.controller_manager.ControllerManagerService/SetControllerVibration',
            controller__manager__pb2.SetControllerVibrationRequest.SerializeToString,
            controller__manager__pb2.SetControllerVibrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayControllerEffect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.controller_manager.ControllerManagerService/PlayControllerEffect',
            controller__manager__pb2.PlayControllerEffectRequest.SerializeToString,
            controller__manager__pb2.PlayControllerEffectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
