# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import controller_manager_pb2 as controller__manager__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in controller_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControllerManagerServiceStub(object):
    """ControllerManager Service - Manages PS Move controllers
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamButtonEvents = channel.stream_stream(
                '/joustmania.controller_manager.ControllerManagerService/StreamButtonEvents',
                request_serializer=controller__manager__pb2.ButtonEventStreamControl.SerializeToString,
                response_deserializer=controller__manager__pb2.ButtonEvent.FromString,
                _registered_method=True)
        self.StreamGameplayData = channel.unary_stream(
                '/joustmania.controller_manager.ControllerManagerService/StreamGameplayData',
                request_serializer=controller__manager__pb2.GameplayStreamRequest.SerializeToString,
                response_deserializer=controller__manager__pb2.GameplayDataUpdate.FromString,
                _registered_method=True)
        self.StreamGameplayDataDynamic = channel.stream_stream(
                '/joustmania.controller_manager.ControllerManagerService/StreamGameplayDataDynamic',
                request_serializer=controller__manager__pb2.GameplayStreamControl.SerializeToString,
                response_deserializer=controller__manager__pb2.GameplayDataUpdate.FromString,
                _registered_method=True)
        self.PlayControllerEffect = channel.unary_unary(
                '/joustmania.controller_manager.ControllerManagerService/PlayControllerEffect',
                request_serializer=controller__manager__pb2.PlayControllerEffectRequest.SerializeToString,
                response_deserializer=controller__manager__pb2.PlayControllerEffectResponse.FromString,
                _registered_method=True)
        self.RenameController = channel.unary_unary(
                '/joustmania.controller_manager.ControllerManagerService/RenameController',
                request_serializer=controller__manager__pb2.RenameControllerRequest.SerializeToString,
                response_deserializer=controller__manager__pb2.RenameControllerResponse.FromString,
                _registered_method=True)


class ControllerManagerServiceServicer(object):
    """ControllerManager Service - Manages PS Move controllers
    """

    def StreamButtonEvents(self, request_iterator, context):
        """Stream button press/release events (Phase 41 - event-driven for menu/UI)
        Phase XX: Made bidirectional for LED state ownership - menu can send base colors and effects
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGameplayData(self, request, context):
        """Stream gameplay data (acceleration/gyro only, Phase 41 - for game modes)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGameplayDataDynamic(self, request_iterator, context):
        """Stream gameplay data with dynamic filtering (Phase 45 - bidirectional streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayControllerEffect(self, request, context):
        """Controller feedback RPCs (Phase 19)
        Play predefined effect (flash, pulse, rainbow, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameController(self, request, context):
        """Rename a controller (set custom human-readable name)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamButtonEvents': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamButtonEvents,
                    request_deserializer=controller__manager__pb2.ButtonEventStreamControl.FromString,
                    response_serializer=controller__manager__pb2.ButtonEvent.SerializeToString,
            ),
            'StreamGameplayData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGameplayData,
                    request_deserializer=controller__manager__pb2.GameplayStreamRequest.FromString,
                    response_serializer=controller__manager__pb2.GameplayDataUpdate.SerializeToString,
            ),
            'StreamGameplayDataDynamic': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamGameplayDataDynamic,
                    request_deserializer=controller__manager__pb2.GameplayStreamControl.FromString,
                    response_serializer=controller__manager__pb2.GameplayDataUpdate.SerializeToString,
            ),
            'PlayControllerEffect': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayControllerEffect,
                    request_deserializer=controller__manager__pb2.PlayControllerEffectRequest.FromString,
                    response_serializer=controller__manager__pb2.PlayControllerEffectResponse.SerializeToString,
            ),
            'RenameController': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameController,
                    request_deserializer=controller__manager__pb2.RenameControllerRequest.FromString,
                    response_serializer=controller__manager__pb2.RenameControllerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'joustmania.controller_manager.ControllerManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('joustmania.controller_manager.ControllerManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControllerManagerService(object):
    """ControllerManager Service - Manages PS Move controllers
    """

    @staticmethod
    def StreamButtonEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/joustmania.controller_manager.ControllerManagerService/StreamButtonEvents',
            controller__manager__pb2.ButtonEventStreamControl.SerializeToString,
            controller__manager__pb2.ButtonEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGameplayData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/joustmania.controller_manager.ControllerManagerService/StreamGameplayData',
            controller__manager__pb2.GameplayStreamRequest.SerializeToString,
            controller__manager__pb2.GameplayDataUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGameplayDataDynamic(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/joustmania.controller_manager.ControllerManagerService/StreamGameplayDataDynamic',
            controller__manager__pb2.GameplayStreamControl.SerializeToString,
            controller__manager__pb2.GameplayDataUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayControllerEffect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.controller_manager.ControllerManagerService/PlayControllerEffect',
            controller__manager__pb2.PlayControllerEffectRequest.SerializeToString,
            controller__manager__pb2.PlayControllerEffectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameController(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.controller_manager.ControllerManagerService/RenameController',
            controller__manager__pb2.RenameControllerRequest.SerializeToString,
            controller__manager__pb2.RenameControllerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
