# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: menu.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'menu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmenu.proto\x12\x0fjoustmania.menu\"\x12\n\x10StartMenuRequest\"3\n\x11StartMenuResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x11\n\x0fStopMenuRequest\"2\n\x10StopMenuResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x19\n\x17StreamMenuEventsRequest\"\x93\x01\n\tMenuEvent\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x32\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32$.joustmania.menu.MenuEvent.DataEntry\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x94\x01\n\x13ProcessInputRequest\x12\x12\n\ninput_type\x18\x01 \x01(\t\x12<\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32..joustmania.menu.ProcessInputRequest.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"6\n\x14ProcessInputResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t*8\n\tMenuState\x12\x0b\n\x07STOPPED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\x11\n\rGAME_STARTING\x10\x02\x32\xeb\x02\n\x0bMenuService\x12R\n\tStartMenu\x12!.joustmania.menu.StartMenuRequest\x1a\".joustmania.menu.StartMenuResponse\x12O\n\x08StopMenu\x12 .joustmania.menu.StopMenuRequest\x1a!.joustmania.menu.StopMenuResponse\x12Z\n\x10StreamMenuEvents\x12(.joustmania.menu.StreamMenuEventsRequest\x1a\x1a.joustmania.menu.MenuEvent0\x01\x12[\n\x0cProcessInput\x12$.joustmania.menu.ProcessInputRequest\x1a%.joustmania.menu.ProcessInputResponseB.Z,github.com/joustmania/connect-proxy/gen/menub\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'menu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/joustmania/connect-proxy/gen/menu'
  _globals['_MENUEVENT_DATAENTRY']._loaded_options = None
  _globals['_MENUEVENT_DATAENTRY']._serialized_options = b'8\001'
  _globals['_PROCESSINPUTREQUEST_DATAENTRY']._loaded_options = None
  _globals['_PROCESSINPUTREQUEST_DATAENTRY']._serialized_options = b'8\001'
  _globals['_MENUSTATE']._serialized_start=559
  _globals['_MENUSTATE']._serialized_end=615
  _globals['_STARTMENUREQUEST']._serialized_start=31
  _globals['_STARTMENUREQUEST']._serialized_end=49
  _globals['_STARTMENURESPONSE']._serialized_start=51
  _globals['_STARTMENURESPONSE']._serialized_end=102
  _globals['_STOPMENUREQUEST']._serialized_start=104
  _globals['_STOPMENUREQUEST']._serialized_end=121
  _globals['_STOPMENURESPONSE']._serialized_start=123
  _globals['_STOPMENURESPONSE']._serialized_end=173
  _globals['_STREAMMENUEVENTSREQUEST']._serialized_start=175
  _globals['_STREAMMENUEVENTSREQUEST']._serialized_end=200
  _globals['_MENUEVENT']._serialized_start=203
  _globals['_MENUEVENT']._serialized_end=350
  _globals['_MENUEVENT_DATAENTRY']._serialized_start=307
  _globals['_MENUEVENT_DATAENTRY']._serialized_end=350
  _globals['_PROCESSINPUTREQUEST']._serialized_start=353
  _globals['_PROCESSINPUTREQUEST']._serialized_end=501
  _globals['_PROCESSINPUTREQUEST_DATAENTRY']._serialized_start=307
  _globals['_PROCESSINPUTREQUEST_DATAENTRY']._serialized_end=350
  _globals['_PROCESSINPUTRESPONSE']._serialized_start=503
  _globals['_PROCESSINPUTRESPONSE']._serialized_end=557
  _globals['_MENUSERVICE']._serialized_start=618
  _globals['_MENUSERVICE']._serialized_end=981
# @@protoc_insertion_point(module_scope)
