# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import menu_pb2 as menu__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in menu_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MenuServiceStub(object):
    """Menu Service - Manages menu UI and user interactions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartMenu = channel.unary_unary(
                '/joustmania.menu.MenuService/StartMenu',
                request_serializer=menu__pb2.StartMenuRequest.SerializeToString,
                response_deserializer=menu__pb2.StartMenuResponse.FromString,
                _registered_method=True)
        self.StopMenu = channel.unary_unary(
                '/joustmania.menu.MenuService/StopMenu',
                request_serializer=menu__pb2.StopMenuRequest.SerializeToString,
                response_deserializer=menu__pb2.StopMenuResponse.FromString,
                _registered_method=True)
        self.GetMenuStatus = channel.unary_unary(
                '/joustmania.menu.MenuService/GetMenuStatus',
                request_serializer=menu__pb2.GetMenuStatusRequest.SerializeToString,
                response_deserializer=menu__pb2.GetMenuStatusResponse.FromString,
                _registered_method=True)
        self.StreamMenuEvents = channel.unary_stream(
                '/joustmania.menu.MenuService/StreamMenuEvents',
                request_serializer=menu__pb2.StreamMenuEventsRequest.SerializeToString,
                response_deserializer=menu__pb2.MenuEvent.FromString,
                _registered_method=True)
        self.ProcessInput = channel.unary_unary(
                '/joustmania.menu.MenuService/ProcessInput',
                request_serializer=menu__pb2.ProcessInputRequest.SerializeToString,
                response_deserializer=menu__pb2.ProcessInputResponse.FromString,
                _registered_method=True)


class MenuServiceServicer(object):
    """Menu Service - Manages menu UI and user interactions
    """

    def StartMenu(self, request, context):
        """Start menu
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopMenu(self, request, context):
        """Stop menu
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMenuStatus(self, request, context):
        """Get menu status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMenuEvents(self, request, context):
        """Stream menu events (button presses, selections)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessInput(self, request, context):
        """Process menu input
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MenuServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartMenu': grpc.unary_unary_rpc_method_handler(
                    servicer.StartMenu,
                    request_deserializer=menu__pb2.StartMenuRequest.FromString,
                    response_serializer=menu__pb2.StartMenuResponse.SerializeToString,
            ),
            'StopMenu': grpc.unary_unary_rpc_method_handler(
                    servicer.StopMenu,
                    request_deserializer=menu__pb2.StopMenuRequest.FromString,
                    response_serializer=menu__pb2.StopMenuResponse.SerializeToString,
            ),
            'GetMenuStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMenuStatus,
                    request_deserializer=menu__pb2.GetMenuStatusRequest.FromString,
                    response_serializer=menu__pb2.GetMenuStatusResponse.SerializeToString,
            ),
            'StreamMenuEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMenuEvents,
                    request_deserializer=menu__pb2.StreamMenuEventsRequest.FromString,
                    response_serializer=menu__pb2.MenuEvent.SerializeToString,
            ),
            'ProcessInput': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessInput,
                    request_deserializer=menu__pb2.ProcessInputRequest.FromString,
                    response_serializer=menu__pb2.ProcessInputResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'joustmania.menu.MenuService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('joustmania.menu.MenuService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MenuService(object):
    """Menu Service - Manages menu UI and user interactions
    """

    @staticmethod
    def StartMenu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.menu.MenuService/StartMenu',
            menu__pb2.StartMenuRequest.SerializeToString,
            menu__pb2.StartMenuResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopMenu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.menu.MenuService/StopMenu',
            menu__pb2.StopMenuRequest.SerializeToString,
            menu__pb2.StopMenuResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMenuStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.menu.MenuService/GetMenuStatus',
            menu__pb2.GetMenuStatusRequest.SerializeToString,
            menu__pb2.GetMenuStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMenuEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/joustmania.menu.MenuService/StreamMenuEvents',
            menu__pb2.StreamMenuEventsRequest.SerializeToString,
            menu__pb2.MenuEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.menu.MenuService/ProcessInput',
            menu__pb2.ProcessInputRequest.SerializeToString,
            menu__pb2.ProcessInputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
