# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import supervisor_pb2 as supervisor__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in supervisor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SupervisorServiceStub(object):
    """Supervisor Service - Monitors and manages all microservices
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProcessStatus = channel.unary_unary(
                '/joustmania.supervisor.SupervisorService/GetProcessStatus',
                request_serializer=supervisor__pb2.GetProcessStatusRequest.SerializeToString,
                response_deserializer=supervisor__pb2.GetProcessStatusResponse.FromString,
                _registered_method=True)
        self.GetAllProcessStatus = channel.unary_unary(
                '/joustmania.supervisor.SupervisorService/GetAllProcessStatus',
                request_serializer=supervisor__pb2.GetAllProcessStatusRequest.SerializeToString,
                response_deserializer=supervisor__pb2.GetAllProcessStatusResponse.FromString,
                _registered_method=True)
        self.RestartProcess = channel.unary_unary(
                '/joustmania.supervisor.SupervisorService/RestartProcess',
                request_serializer=supervisor__pb2.RestartProcessRequest.SerializeToString,
                response_deserializer=supervisor__pb2.RestartProcessResponse.FromString,
                _registered_method=True)
        self.GetHealthSummary = channel.unary_unary(
                '/joustmania.supervisor.SupervisorService/GetHealthSummary',
                request_serializer=supervisor__pb2.GetHealthSummaryRequest.SerializeToString,
                response_deserializer=supervisor__pb2.GetHealthSummaryResponse.FromString,
                _registered_method=True)
        self.StreamProcessUpdates = channel.unary_stream(
                '/joustmania.supervisor.SupervisorService/StreamProcessUpdates',
                request_serializer=supervisor__pb2.StreamUpdatesRequest.SerializeToString,
                response_deserializer=supervisor__pb2.ProcessStatusUpdate.FromString,
                _registered_method=True)


class SupervisorServiceServicer(object):
    """Supervisor Service - Monitors and manages all microservices
    """

    def GetProcessStatus(self, request, context):
        """Get status of a specific process
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllProcessStatus(self, request, context):
        """Get status of all processes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestartProcess(self, request, context):
        """Restart a failed process
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealthSummary(self, request, context):
        """Get system health summary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamProcessUpdates(self, request, context):
        """Stream process status updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SupervisorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProcessStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessStatus,
                    request_deserializer=supervisor__pb2.GetProcessStatusRequest.FromString,
                    response_serializer=supervisor__pb2.GetProcessStatusResponse.SerializeToString,
            ),
            'GetAllProcessStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllProcessStatus,
                    request_deserializer=supervisor__pb2.GetAllProcessStatusRequest.FromString,
                    response_serializer=supervisor__pb2.GetAllProcessStatusResponse.SerializeToString,
            ),
            'RestartProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartProcess,
                    request_deserializer=supervisor__pb2.RestartProcessRequest.FromString,
                    response_serializer=supervisor__pb2.RestartProcessResponse.SerializeToString,
            ),
            'GetHealthSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealthSummary,
                    request_deserializer=supervisor__pb2.GetHealthSummaryRequest.FromString,
                    response_serializer=supervisor__pb2.GetHealthSummaryResponse.SerializeToString,
            ),
            'StreamProcessUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamProcessUpdates,
                    request_deserializer=supervisor__pb2.StreamUpdatesRequest.FromString,
                    response_serializer=supervisor__pb2.ProcessStatusUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'joustmania.supervisor.SupervisorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('joustmania.supervisor.SupervisorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SupervisorService(object):
    """Supervisor Service - Monitors and manages all microservices
    """

    @staticmethod
    def GetProcessStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.supervisor.SupervisorService/GetProcessStatus',
            supervisor__pb2.GetProcessStatusRequest.SerializeToString,
            supervisor__pb2.GetProcessStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllProcessStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.supervisor.SupervisorService/GetAllProcessStatus',
            supervisor__pb2.GetAllProcessStatusRequest.SerializeToString,
            supervisor__pb2.GetAllProcessStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestartProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.supervisor.SupervisorService/RestartProcess',
            supervisor__pb2.RestartProcessRequest.SerializeToString,
            supervisor__pb2.RestartProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealthSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/joustmania.supervisor.SupervisorService/GetHealthSummary',
            supervisor__pb2.GetHealthSummaryRequest.SerializeToString,
            supervisor__pb2.GetHealthSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamProcessUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/joustmania.supervisor.SupervisorService/StreamProcessUpdates',
            supervisor__pb2.StreamUpdatesRequest.SerializeToString,
            supervisor__pb2.ProcessStatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
